### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sleeptillseven** [nathans/lxx-swete#1]
Hi Nathan

You repos has no license explicitly mentioned. One gets the idea, that it's absolutely free. There is a similar Repo https://github.com/eliranwong/LXX-Swete-1930 which claims same sources but ships with GPL. Because that's a place I don't want to do, I started to type the text from the book. Of course, that's a time consuming and painful task.

What I want to figure out is, whether bibleworks put that out with no license attached and in that respect Eliran Wong put the GPL in his own interest or the source itself is attached to the GPL license (and you forgot to make that explicit).

Do you plan to set a license to your repo at all?

Thank for your time and effort.

Cheers,
Chris

**Comment by nathans** [comment]
I'm on vacation and can correspond more extensively later. However I consider the Swete LXX to be public domain. I don't have any copyrights in the text. I had made some effort to correct the OCR'd output of the open Greek and Latin Project's effort, but when I found out that Elian had already finished, I switched to his text. I was not aware of any copyright claims being made by Elian to allow for GPL licensing. For what it's worth, I don't think transcription really warrants copyrights, but I am not a lawyer. 




On June 20, 2019 3:55:03 PM EDT, Christoph Jasinski <notifications@github.com> wrote:
>Hi Nathan
>
>You repos has no license explicitly mentioned. One gets the idea, that
>it's absolutely free. There is a similar Repo
>https://github.com/eliranwong/LXX-Swete-1930 which claims same sources
>but ships with GPL. Because that's a place I don't want to do, I
>started to type the text from the book. Of course, that's a time
>consuming and painful task.
>
>What I want to figure out is, whether bibleworks put that out with no
>license attached and in that respect Eliran Wong put the GPL in his own
>interest or the source itself is attached to the GPL license (and you
>forgot to make that explicit).
>
>Do you plan to set a license to your repo at all?
>
>Thank for your time and effort.
>
>Cheers,
>Chris

-- 
Nathan D. Smith

**Comment by nathans** [comment]
I am happy to report that the text has been rebased from a source which does not claim GPL. :-)
